alter table if exists test drop constraint if exists user_fk;
alter table if exists test_result drop constraint if exists test_fk;
alter table if exists test_result drop constraint if exists user_fk;

drop table if exists test cascade;
drop table if exists test_result cascade;

create table test
(
    id      int8 generated by default as identity,
    user_id int8         not null,
    "name"  varchar(255) not null,
    primary key (id)
);

create table test_result
(
    id      int8 generated by default as identity,
    test_id int8 not null,
    user_id int8 not null,
    score   int8 not null,
    primary key (id)
);

alter table if exists test add constraint user_fk foreign key (user_id) references users;
alter table if exists test_result add constraint test_fk foreign key (test_id) references test;
alter table if exists test_result add constraint user_fk foreign key (user_id) references users;
